/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LinkSchoolRouteImport } from './routes/link-school'
import { Route as ComingSoonRouteImport } from './routes/coming-soon'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthedDashboardRouteRouteImport } from './routes/_authed/dashboard/route'
import { Route as AuthedDashboardIndexRouteImport } from './routes/_authed/dashboard/index'
import { Route as AuthInviteAcceptRouteImport } from './routes/auth/invite/accept'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'
import { Route as AuthedDashboardStudentsRouteRouteImport } from './routes/_authed/dashboard/students/route'
import { Route as AuthedDashboardSettingsRouteRouteImport } from './routes/_authed/dashboard/settings/route'
import { Route as AuthedDashboardExamsRouteRouteImport } from './routes/_authed/dashboard/exams/route'
import { Route as AuthedDashboardBillingRouteRouteImport } from './routes/_authed/dashboard/billing/route'
import { Route as AuthedDashboardStudentsIndexRouteImport } from './routes/_authed/dashboard/students/index'
import { Route as AuthedDashboardSettingsIndexRouteImport } from './routes/_authed/dashboard/settings/index'
import { Route as AuthedDashboardExamsIndexRouteImport } from './routes/_authed/dashboard/exams/index'
import { Route as AuthedDashboardClassesIndexRouteImport } from './routes/_authed/dashboard/classes/index'
import { Route as AuthedDashboardStudentsAttendanceRouteImport } from './routes/_authed/dashboard/students/attendance'
import { Route as AuthedDashboardStudentsAddRouteImport } from './routes/_authed/dashboard/students/add'
import { Route as AuthedDashboardExamsScoresRouteImport } from './routes/_authed/dashboard/exams/scores'
import { Route as AuthedDashboardBillingFeesRouteImport } from './routes/_authed/dashboard/billing/fees'
import { Route as AuthedDashboardStudentsStudentIdIndexRouteImport } from './routes/_authed/dashboard/students/$studentId/index'
import { Route as AuthedDashboardBillingInvoicesIndexRouteImport } from './routes/_authed/dashboard/billing/invoices/index'
import { Route as AuthedDashboardStudentsStudentIdEditRouteImport } from './routes/_authed/dashboard/students/$studentId/edit'
import { Route as AuthedDashboardBillingInvoicesInvoiceIdRouteImport } from './routes/_authed/dashboard/billing/invoices/$invoiceId'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkSchoolRoute = LinkSchoolRouteImport.update({
  id: '/link-school',
  path: '/link-school',
  getParentRoute: () => rootRouteImport,
} as any)
const ComingSoonRoute = ComingSoonRouteImport.update({
  id: '/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthedDashboardRouteRoute = AuthedDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedDashboardIndexRoute = AuthedDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedDashboardRouteRoute,
} as any)
const AuthInviteAcceptRoute = AuthInviteAcceptRouteImport.update({
  id: '/auth/invite/accept',
  path: '/auth/invite/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardStudentsRouteRoute =
  AuthedDashboardStudentsRouteRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthedDashboardRouteRoute,
  } as any)
const AuthedDashboardSettingsRouteRoute =
  AuthedDashboardSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthedDashboardRouteRoute,
  } as any)
const AuthedDashboardExamsRouteRoute =
  AuthedDashboardExamsRouteRouteImport.update({
    id: '/exams',
    path: '/exams',
    getParentRoute: () => AuthedDashboardRouteRoute,
  } as any)
const AuthedDashboardBillingRouteRoute =
  AuthedDashboardBillingRouteRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthedDashboardRouteRoute,
  } as any)
const AuthedDashboardStudentsIndexRoute =
  AuthedDashboardStudentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedDashboardStudentsRouteRoute,
  } as any)
const AuthedDashboardSettingsIndexRoute =
  AuthedDashboardSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedDashboardSettingsRouteRoute,
  } as any)
const AuthedDashboardExamsIndexRoute =
  AuthedDashboardExamsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedDashboardExamsRouteRoute,
  } as any)
const AuthedDashboardClassesIndexRoute =
  AuthedDashboardClassesIndexRouteImport.update({
    id: '/classes/',
    path: '/classes/',
    getParentRoute: () => AuthedDashboardRouteRoute,
  } as any)
const AuthedDashboardStudentsAttendanceRoute =
  AuthedDashboardStudentsAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AuthedDashboardStudentsRouteRoute,
  } as any)
const AuthedDashboardStudentsAddRoute =
  AuthedDashboardStudentsAddRouteImport.update({
    id: '/add',
    path: '/add',
    getParentRoute: () => AuthedDashboardStudentsRouteRoute,
  } as any)
const AuthedDashboardExamsScoresRoute =
  AuthedDashboardExamsScoresRouteImport.update({
    id: '/scores',
    path: '/scores',
    getParentRoute: () => AuthedDashboardExamsRouteRoute,
  } as any)
const AuthedDashboardBillingFeesRoute =
  AuthedDashboardBillingFeesRouteImport.update({
    id: '/fees',
    path: '/fees',
    getParentRoute: () => AuthedDashboardBillingRouteRoute,
  } as any)
const AuthedDashboardStudentsStudentIdIndexRoute =
  AuthedDashboardStudentsStudentIdIndexRouteImport.update({
    id: '/$studentId/',
    path: '/$studentId/',
    getParentRoute: () => AuthedDashboardStudentsRouteRoute,
  } as any)
const AuthedDashboardBillingInvoicesIndexRoute =
  AuthedDashboardBillingInvoicesIndexRouteImport.update({
    id: '/invoices/',
    path: '/invoices/',
    getParentRoute: () => AuthedDashboardBillingRouteRoute,
  } as any)
const AuthedDashboardStudentsStudentIdEditRoute =
  AuthedDashboardStudentsStudentIdEditRouteImport.update({
    id: '/$studentId/edit',
    path: '/$studentId/edit',
    getParentRoute: () => AuthedDashboardStudentsRouteRoute,
  } as any)
const AuthedDashboardBillingInvoicesInvoiceIdRoute =
  AuthedDashboardBillingInvoicesInvoiceIdRouteImport.update({
    id: '/invoices/$invoiceId',
    path: '/invoices/$invoiceId',
    getParentRoute: () => AuthedDashboardBillingRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coming-soon': typeof ComingSoonRoute
  '/link-school': typeof LinkSchoolRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/test': typeof TestRoute
  '/dashboard': typeof AuthedDashboardRouteRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/api/$': typeof ApiSplatRoute
  '/dashboard/billing': typeof AuthedDashboardBillingRouteRouteWithChildren
  '/dashboard/exams': typeof AuthedDashboardExamsRouteRouteWithChildren
  '/dashboard/settings': typeof AuthedDashboardSettingsRouteRouteWithChildren
  '/dashboard/students': typeof AuthedDashboardStudentsRouteRouteWithChildren
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/auth/invite/accept': typeof AuthInviteAcceptRoute
  '/dashboard/': typeof AuthedDashboardIndexRoute
  '/dashboard/billing/fees': typeof AuthedDashboardBillingFeesRoute
  '/dashboard/exams/scores': typeof AuthedDashboardExamsScoresRoute
  '/dashboard/students/add': typeof AuthedDashboardStudentsAddRoute
  '/dashboard/students/attendance': typeof AuthedDashboardStudentsAttendanceRoute
  '/dashboard/classes/': typeof AuthedDashboardClassesIndexRoute
  '/dashboard/exams/': typeof AuthedDashboardExamsIndexRoute
  '/dashboard/settings/': typeof AuthedDashboardSettingsIndexRoute
  '/dashboard/students/': typeof AuthedDashboardStudentsIndexRoute
  '/dashboard/billing/invoices/$invoiceId': typeof AuthedDashboardBillingInvoicesInvoiceIdRoute
  '/dashboard/students/$studentId/edit': typeof AuthedDashboardStudentsStudentIdEditRoute
  '/dashboard/billing/invoices/': typeof AuthedDashboardBillingInvoicesIndexRoute
  '/dashboard/students/$studentId/': typeof AuthedDashboardStudentsStudentIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coming-soon': typeof ComingSoonRoute
  '/link-school': typeof LinkSchoolRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/test': typeof TestRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/api/$': typeof ApiSplatRoute
  '/dashboard/billing': typeof AuthedDashboardBillingRouteRouteWithChildren
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/auth/invite/accept': typeof AuthInviteAcceptRoute
  '/dashboard': typeof AuthedDashboardIndexRoute
  '/dashboard/billing/fees': typeof AuthedDashboardBillingFeesRoute
  '/dashboard/exams/scores': typeof AuthedDashboardExamsScoresRoute
  '/dashboard/students/add': typeof AuthedDashboardStudentsAddRoute
  '/dashboard/students/attendance': typeof AuthedDashboardStudentsAttendanceRoute
  '/dashboard/classes': typeof AuthedDashboardClassesIndexRoute
  '/dashboard/exams': typeof AuthedDashboardExamsIndexRoute
  '/dashboard/settings': typeof AuthedDashboardSettingsIndexRoute
  '/dashboard/students': typeof AuthedDashboardStudentsIndexRoute
  '/dashboard/billing/invoices/$invoiceId': typeof AuthedDashboardBillingInvoicesInvoiceIdRoute
  '/dashboard/students/$studentId/edit': typeof AuthedDashboardStudentsStudentIdEditRoute
  '/dashboard/billing/invoices': typeof AuthedDashboardBillingInvoicesIndexRoute
  '/dashboard/students/$studentId': typeof AuthedDashboardStudentsStudentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/coming-soon': typeof ComingSoonRoute
  '/link-school': typeof LinkSchoolRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/test': typeof TestRoute
  '/_authed/dashboard': typeof AuthedDashboardRouteRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/api/$': typeof ApiSplatRoute
  '/_authed/dashboard/billing': typeof AuthedDashboardBillingRouteRouteWithChildren
  '/_authed/dashboard/exams': typeof AuthedDashboardExamsRouteRouteWithChildren
  '/_authed/dashboard/settings': typeof AuthedDashboardSettingsRouteRouteWithChildren
  '/_authed/dashboard/students': typeof AuthedDashboardStudentsRouteRouteWithChildren
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/auth/invite/accept': typeof AuthInviteAcceptRoute
  '/_authed/dashboard/': typeof AuthedDashboardIndexRoute
  '/_authed/dashboard/billing/fees': typeof AuthedDashboardBillingFeesRoute
  '/_authed/dashboard/exams/scores': typeof AuthedDashboardExamsScoresRoute
  '/_authed/dashboard/students/add': typeof AuthedDashboardStudentsAddRoute
  '/_authed/dashboard/students/attendance': typeof AuthedDashboardStudentsAttendanceRoute
  '/_authed/dashboard/classes/': typeof AuthedDashboardClassesIndexRoute
  '/_authed/dashboard/exams/': typeof AuthedDashboardExamsIndexRoute
  '/_authed/dashboard/settings/': typeof AuthedDashboardSettingsIndexRoute
  '/_authed/dashboard/students/': typeof AuthedDashboardStudentsIndexRoute
  '/_authed/dashboard/billing/invoices/$invoiceId': typeof AuthedDashboardBillingInvoicesInvoiceIdRoute
  '/_authed/dashboard/students/$studentId/edit': typeof AuthedDashboardStudentsStudentIdEditRoute
  '/_authed/dashboard/billing/invoices/': typeof AuthedDashboardBillingInvoicesIndexRoute
  '/_authed/dashboard/students/$studentId/': typeof AuthedDashboardStudentsStudentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coming-soon'
    | '/link-school'
    | '/onboarding'
    | '/register'
    | '/test'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/api/$'
    | '/dashboard/billing'
    | '/dashboard/exams'
    | '/dashboard/settings'
    | '/dashboard/students'
    | '/api/rpc/$'
    | '/auth/invite/accept'
    | '/dashboard/'
    | '/dashboard/billing/fees'
    | '/dashboard/exams/scores'
    | '/dashboard/students/add'
    | '/dashboard/students/attendance'
    | '/dashboard/classes/'
    | '/dashboard/exams/'
    | '/dashboard/settings/'
    | '/dashboard/students/'
    | '/dashboard/billing/invoices/$invoiceId'
    | '/dashboard/students/$studentId/edit'
    | '/dashboard/billing/invoices/'
    | '/dashboard/students/$studentId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coming-soon'
    | '/link-school'
    | '/onboarding'
    | '/register'
    | '/test'
    | '/forgot-password'
    | '/login'
    | '/api/$'
    | '/dashboard/billing'
    | '/api/rpc/$'
    | '/auth/invite/accept'
    | '/dashboard'
    | '/dashboard/billing/fees'
    | '/dashboard/exams/scores'
    | '/dashboard/students/add'
    | '/dashboard/students/attendance'
    | '/dashboard/classes'
    | '/dashboard/exams'
    | '/dashboard/settings'
    | '/dashboard/students'
    | '/dashboard/billing/invoices/$invoiceId'
    | '/dashboard/students/$studentId/edit'
    | '/dashboard/billing/invoices'
    | '/dashboard/students/$studentId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_authed'
    | '/coming-soon'
    | '/link-school'
    | '/onboarding'
    | '/register'
    | '/test'
    | '/_authed/dashboard'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/api/$'
    | '/_authed/dashboard/billing'
    | '/_authed/dashboard/exams'
    | '/_authed/dashboard/settings'
    | '/_authed/dashboard/students'
    | '/api/rpc/$'
    | '/auth/invite/accept'
    | '/_authed/dashboard/'
    | '/_authed/dashboard/billing/fees'
    | '/_authed/dashboard/exams/scores'
    | '/_authed/dashboard/students/add'
    | '/_authed/dashboard/students/attendance'
    | '/_authed/dashboard/classes/'
    | '/_authed/dashboard/exams/'
    | '/_authed/dashboard/settings/'
    | '/_authed/dashboard/students/'
    | '/_authed/dashboard/billing/invoices/$invoiceId'
    | '/_authed/dashboard/students/$studentId/edit'
    | '/_authed/dashboard/billing/invoices/'
    | '/_authed/dashboard/students/$studentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  ComingSoonRoute: typeof ComingSoonRoute
  LinkSchoolRoute: typeof LinkSchoolRoute
  OnboardingRoute: typeof OnboardingRoute
  RegisterRoute: typeof RegisterRoute
  TestRoute: typeof TestRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  AuthInviteAcceptRoute: typeof AuthInviteAcceptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/link-school': {
      id: '/link-school'
      path: '/link-school'
      fullPath: '/link-school'
      preLoaderRoute: typeof LinkSchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coming-soon': {
      id: '/coming-soon'
      path: '/coming-soon'
      fullPath: '/coming-soon'
      preLoaderRoute: typeof ComingSoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/dashboard/': {
      id: '/_authed/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthedDashboardIndexRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
    '/auth/invite/accept': {
      id: '/auth/invite/accept'
      path: '/auth/invite/accept'
      fullPath: '/auth/invite/accept'
      preLoaderRoute: typeof AuthInviteAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard/students': {
      id: '/_authed/dashboard/students'
      path: '/students'
      fullPath: '/dashboard/students'
      preLoaderRoute: typeof AuthedDashboardStudentsRouteRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
    '/_authed/dashboard/settings': {
      id: '/_authed/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthedDashboardSettingsRouteRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
    '/_authed/dashboard/exams': {
      id: '/_authed/dashboard/exams'
      path: '/exams'
      fullPath: '/dashboard/exams'
      preLoaderRoute: typeof AuthedDashboardExamsRouteRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
    '/_authed/dashboard/billing': {
      id: '/_authed/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof AuthedDashboardBillingRouteRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
    '/_authed/dashboard/students/': {
      id: '/_authed/dashboard/students/'
      path: '/'
      fullPath: '/dashboard/students/'
      preLoaderRoute: typeof AuthedDashboardStudentsIndexRouteImport
      parentRoute: typeof AuthedDashboardStudentsRouteRoute
    }
    '/_authed/dashboard/settings/': {
      id: '/_authed/dashboard/settings/'
      path: '/'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof AuthedDashboardSettingsIndexRouteImport
      parentRoute: typeof AuthedDashboardSettingsRouteRoute
    }
    '/_authed/dashboard/exams/': {
      id: '/_authed/dashboard/exams/'
      path: '/'
      fullPath: '/dashboard/exams/'
      preLoaderRoute: typeof AuthedDashboardExamsIndexRouteImport
      parentRoute: typeof AuthedDashboardExamsRouteRoute
    }
    '/_authed/dashboard/classes/': {
      id: '/_authed/dashboard/classes/'
      path: '/classes'
      fullPath: '/dashboard/classes/'
      preLoaderRoute: typeof AuthedDashboardClassesIndexRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
    '/_authed/dashboard/students/attendance': {
      id: '/_authed/dashboard/students/attendance'
      path: '/attendance'
      fullPath: '/dashboard/students/attendance'
      preLoaderRoute: typeof AuthedDashboardStudentsAttendanceRouteImport
      parentRoute: typeof AuthedDashboardStudentsRouteRoute
    }
    '/_authed/dashboard/students/add': {
      id: '/_authed/dashboard/students/add'
      path: '/add'
      fullPath: '/dashboard/students/add'
      preLoaderRoute: typeof AuthedDashboardStudentsAddRouteImport
      parentRoute: typeof AuthedDashboardStudentsRouteRoute
    }
    '/_authed/dashboard/exams/scores': {
      id: '/_authed/dashboard/exams/scores'
      path: '/scores'
      fullPath: '/dashboard/exams/scores'
      preLoaderRoute: typeof AuthedDashboardExamsScoresRouteImport
      parentRoute: typeof AuthedDashboardExamsRouteRoute
    }
    '/_authed/dashboard/billing/fees': {
      id: '/_authed/dashboard/billing/fees'
      path: '/fees'
      fullPath: '/dashboard/billing/fees'
      preLoaderRoute: typeof AuthedDashboardBillingFeesRouteImport
      parentRoute: typeof AuthedDashboardBillingRouteRoute
    }
    '/_authed/dashboard/students/$studentId/': {
      id: '/_authed/dashboard/students/$studentId/'
      path: '/$studentId'
      fullPath: '/dashboard/students/$studentId/'
      preLoaderRoute: typeof AuthedDashboardStudentsStudentIdIndexRouteImport
      parentRoute: typeof AuthedDashboardStudentsRouteRoute
    }
    '/_authed/dashboard/billing/invoices/': {
      id: '/_authed/dashboard/billing/invoices/'
      path: '/invoices'
      fullPath: '/dashboard/billing/invoices/'
      preLoaderRoute: typeof AuthedDashboardBillingInvoicesIndexRouteImport
      parentRoute: typeof AuthedDashboardBillingRouteRoute
    }
    '/_authed/dashboard/students/$studentId/edit': {
      id: '/_authed/dashboard/students/$studentId/edit'
      path: '/$studentId/edit'
      fullPath: '/dashboard/students/$studentId/edit'
      preLoaderRoute: typeof AuthedDashboardStudentsStudentIdEditRouteImport
      parentRoute: typeof AuthedDashboardStudentsRouteRoute
    }
    '/_authed/dashboard/billing/invoices/$invoiceId': {
      id: '/_authed/dashboard/billing/invoices/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/dashboard/billing/invoices/$invoiceId'
      preLoaderRoute: typeof AuthedDashboardBillingInvoicesInvoiceIdRouteImport
      parentRoute: typeof AuthedDashboardBillingRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AuthedDashboardBillingRouteRouteChildren {
  AuthedDashboardBillingFeesRoute: typeof AuthedDashboardBillingFeesRoute
  AuthedDashboardBillingInvoicesInvoiceIdRoute: typeof AuthedDashboardBillingInvoicesInvoiceIdRoute
  AuthedDashboardBillingInvoicesIndexRoute: typeof AuthedDashboardBillingInvoicesIndexRoute
}

const AuthedDashboardBillingRouteRouteChildren: AuthedDashboardBillingRouteRouteChildren =
  {
    AuthedDashboardBillingFeesRoute: AuthedDashboardBillingFeesRoute,
    AuthedDashboardBillingInvoicesInvoiceIdRoute:
      AuthedDashboardBillingInvoicesInvoiceIdRoute,
    AuthedDashboardBillingInvoicesIndexRoute:
      AuthedDashboardBillingInvoicesIndexRoute,
  }

const AuthedDashboardBillingRouteRouteWithChildren =
  AuthedDashboardBillingRouteRoute._addFileChildren(
    AuthedDashboardBillingRouteRouteChildren,
  )

interface AuthedDashboardExamsRouteRouteChildren {
  AuthedDashboardExamsScoresRoute: typeof AuthedDashboardExamsScoresRoute
  AuthedDashboardExamsIndexRoute: typeof AuthedDashboardExamsIndexRoute
}

const AuthedDashboardExamsRouteRouteChildren: AuthedDashboardExamsRouteRouteChildren =
  {
    AuthedDashboardExamsScoresRoute: AuthedDashboardExamsScoresRoute,
    AuthedDashboardExamsIndexRoute: AuthedDashboardExamsIndexRoute,
  }

const AuthedDashboardExamsRouteRouteWithChildren =
  AuthedDashboardExamsRouteRoute._addFileChildren(
    AuthedDashboardExamsRouteRouteChildren,
  )

interface AuthedDashboardSettingsRouteRouteChildren {
  AuthedDashboardSettingsIndexRoute: typeof AuthedDashboardSettingsIndexRoute
}

const AuthedDashboardSettingsRouteRouteChildren: AuthedDashboardSettingsRouteRouteChildren =
  {
    AuthedDashboardSettingsIndexRoute: AuthedDashboardSettingsIndexRoute,
  }

const AuthedDashboardSettingsRouteRouteWithChildren =
  AuthedDashboardSettingsRouteRoute._addFileChildren(
    AuthedDashboardSettingsRouteRouteChildren,
  )

interface AuthedDashboardStudentsRouteRouteChildren {
  AuthedDashboardStudentsAddRoute: typeof AuthedDashboardStudentsAddRoute
  AuthedDashboardStudentsAttendanceRoute: typeof AuthedDashboardStudentsAttendanceRoute
  AuthedDashboardStudentsIndexRoute: typeof AuthedDashboardStudentsIndexRoute
  AuthedDashboardStudentsStudentIdEditRoute: typeof AuthedDashboardStudentsStudentIdEditRoute
  AuthedDashboardStudentsStudentIdIndexRoute: typeof AuthedDashboardStudentsStudentIdIndexRoute
}

const AuthedDashboardStudentsRouteRouteChildren: AuthedDashboardStudentsRouteRouteChildren =
  {
    AuthedDashboardStudentsAddRoute: AuthedDashboardStudentsAddRoute,
    AuthedDashboardStudentsAttendanceRoute:
      AuthedDashboardStudentsAttendanceRoute,
    AuthedDashboardStudentsIndexRoute: AuthedDashboardStudentsIndexRoute,
    AuthedDashboardStudentsStudentIdEditRoute:
      AuthedDashboardStudentsStudentIdEditRoute,
    AuthedDashboardStudentsStudentIdIndexRoute:
      AuthedDashboardStudentsStudentIdIndexRoute,
  }

const AuthedDashboardStudentsRouteRouteWithChildren =
  AuthedDashboardStudentsRouteRoute._addFileChildren(
    AuthedDashboardStudentsRouteRouteChildren,
  )

interface AuthedDashboardRouteRouteChildren {
  AuthedDashboardBillingRouteRoute: typeof AuthedDashboardBillingRouteRouteWithChildren
  AuthedDashboardExamsRouteRoute: typeof AuthedDashboardExamsRouteRouteWithChildren
  AuthedDashboardSettingsRouteRoute: typeof AuthedDashboardSettingsRouteRouteWithChildren
  AuthedDashboardStudentsRouteRoute: typeof AuthedDashboardStudentsRouteRouteWithChildren
  AuthedDashboardIndexRoute: typeof AuthedDashboardIndexRoute
  AuthedDashboardClassesIndexRoute: typeof AuthedDashboardClassesIndexRoute
}

const AuthedDashboardRouteRouteChildren: AuthedDashboardRouteRouteChildren = {
  AuthedDashboardBillingRouteRoute:
    AuthedDashboardBillingRouteRouteWithChildren,
  AuthedDashboardExamsRouteRoute: AuthedDashboardExamsRouteRouteWithChildren,
  AuthedDashboardSettingsRouteRoute:
    AuthedDashboardSettingsRouteRouteWithChildren,
  AuthedDashboardStudentsRouteRoute:
    AuthedDashboardStudentsRouteRouteWithChildren,
  AuthedDashboardIndexRoute: AuthedDashboardIndexRoute,
  AuthedDashboardClassesIndexRoute: AuthedDashboardClassesIndexRoute,
}

const AuthedDashboardRouteRouteWithChildren =
  AuthedDashboardRouteRoute._addFileChildren(AuthedDashboardRouteRouteChildren)

interface AuthedRouteRouteChildren {
  AuthedDashboardRouteRoute: typeof AuthedDashboardRouteRouteWithChildren
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedDashboardRouteRoute: AuthedDashboardRouteRouteWithChildren,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  ComingSoonRoute: ComingSoonRoute,
  LinkSchoolRoute: LinkSchoolRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
  TestRoute: TestRoute,
  ApiSplatRoute: ApiSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  AuthInviteAcceptRoute: AuthInviteAcceptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
